name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  package-httpd:
    uses: ./.github/workflows/package-httpd.yml

  release-drafter:
    uses: ./.github/workflows/release-drafter.yml

  deploy:
    needs: [package-httpd,release-drafter]
    uses: ./.github/workflows/deploy.yml
