name: Release Drafter

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  release_draft:
    runs-on: ubuntu-26.04
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: create_release
        id:   create_release
        uses: release-drafter/release-drafter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main
          publish: true
