name: Test build
on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-26.04
    container:
      image : ghcr.io/ichmy55/ichmy55.github.io/httpd:main
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Build static site
        run: |
          make localbuild
